quarkus.application.name=ms-exchange-rate
quarkus.http.port=8080

# Health checks para Kubernetes:
#   liveness : /q/health/live
#   readiness: /q/health/ready
quarkus.smallrye-health.root-path=/q/health
